name: Release (GitHub/PyPI) and Deploy Docs

on:
  push:

jobs:
  build-release:
    uses: ycexiao/release-scripts/.github/workflows/_build-wheel-release-upload.yml@main
    with:
      project: diffpy.pdffit2
      c_extension: true
      maintainer_GITHUB_username: ycexiao
