name: Release (GitHub/PyPI) and Deploy Docs

on:
  push:

jobs:
  build-release:
    uses: ycexiao/release-scripts/.github/workflows/_build-wheel-release-upload.yml@test-workflow
    with:
      project: diffpy.pdffit2
      c_extension: true
      maintainer_GITHUB_username: ycexiao
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
